config/routes.rb
Rails.application.routes.draw do
  root to: "homes#top"
  get '/homes/about', as: "about"
  #顧客用
  # URL /customers/sign_in ...
  devise_for :customers, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

  scope module: :public do
    resources :items, only:[:index, :show]
    resources :cart_items, only:[:index, :update, :destroy, :create]do
      collection do
        delete 'destroy_all'
      end
    end
    resources :orders, only:[:new, :index, :show, :create]do
      collection do
        post 'confirm'
        get 'complete'
      end
    end
    get '/customers/my_page' => 'customers#show', as: "customer"
    get '/customers/information/edit' => 'customers#edit', as: "edit_customer"
    patch '/customers/information' => 'customers#update', as: "update_customer"
    get '/customers/unsubscribe', as: "unsubscribe_customer"
    patch '/customers/withdraw', as: "withdraw_customer"
  end

  #管理者用
  # URL /admin/sign_in ...
  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }
  namespace :admin do
    root to: "homes#top"
    resources :items, only:[:index, :new, :show, :edit, :create, :update]
    resources :customers, only:[:index, :show, :edit, :update]
    resources :orders, only:[:show, :update]
  end

end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  has_one_attached :image
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :customer
  belongs_to :item

  def sub_total
    item.with_tax_price * amount
  end
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :cart_items
  has_many :orders

  def full_name
    self.last_name + " " + self.first_name
  end

  def full_name_kana
    self.last_name_kana + " " + self.first_name_kana
  end

  def withdraw_status
    if is_deleted == false
      "有効"
    else
      "退会"
    end
  end
end

app/models/item.rb
class Item < ApplicationRecord
  has_many :cart_items
  has_many :order_details
  
  has_one_attached :image
  
  validates :image       , presence: true
  validates :name        , presence: true
  validates :introduction, presence: true
  validates :price       , presence: true

  def with_tax_price
    tax = 1.10
    (price * tax).round
  end
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :customer
  has_many :order_details
  
  enum payment_method: { credit_card: 0, transfer: 1}
  
end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
  belongs_to :order
  belongs_to :item
end

app/controllers/admin/confirmations_controller.rb
# frozen_string_literal: true

class Admin::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController
  before_action :authenticate_admin!
  
  def index
    @customers = Customer.page(params[:page]).per(10)
  end

  def show
    @customer = Customer.find(params[:id])
  end

  def edit
    @customer = Customer.find(params[:id])
  end

  def update
    @customer = Customer.find(params[:id])
    @customer.update(customer_params)
    redirect_to admin_customer_path
  end


  private
  def customer_params
    params.require(:customer).permit(:last_name, :first_name, :last_name_kana, :first_name_kana, :postal_code, :address, :telephone_number, :email, :is_deleted)
  end
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  before_action :authenticate_admin!
  
  def top
    @orders = Order.page(params[:page]).per(10)
    @total_amount = 0
  end
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  before_action :authenticate_admin!
  
  def index
    @items = Item.page(params[:page]).per(10)
  end

  def new
    @item = Item.new
  end

  def create
    @item = Item.new(item_params)
    if @item.save
      redirect_to admin_item_path(@item.id)
    else
      render :new
    end
  end

  def show
    @item = Item.find(params[:id])
  end

  def edit
    @item = Item.find(params[:id])
  end

  def update
    @item = Item.find(params[:id])
    @item.update(item_params)
    redirect_to admin_item_path
  end


  private
  def item_params
    params.require(:item).permit(:image, :name, :introduction, :price)
  end
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
  before_action :authenticate_admin!

  def show
    @order = Order.find(params[:id])
    @total_price = 0
  end

  def update
  end
end

app/controllers/admin/passwords_controller.rb
# frozen_string_literal: true

class Admin::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/admin/sessions_controller.rb
# frozen_string_literal: true

class Admin::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # def after_sign_in_path_for(resource)
    # 注文履歴一覧（管理者トップページへ）
  # end

  def after_sign_out_path_for(resource)
    new_admin_session_path
  end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/admin/unlocks_controller.rb
# frozen_string_literal: true

class Admin::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
    @items = Item.limit(4).order(:created_at)
  end

  def about
  end
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/admin/customers/edit.html.erb
<div class="container">
  <div class="row">
    <h3 class="bg-light"><%= @customer.full_name %>さんの会員情報編集</h3>
  </div>
  <%= form_with model: @customer, url: admin_customer_path, method: :patch do |f| %>
  <div class="row">
    <table class="table table-borderless table-sm">
      <tr>
        <td>会員ID</td>
        <td><%= @customer.id %></td>
      </tr>
      <tr>
        <td>氏名</td>
        <td><%= f.text_area :last_name,class:"form-control" %></td>
        <td><%= f.text_area :first_name,class:"form-control" %></td>
      </tr>
      <tr>
        <td>フリガナ</td>
        <td><%= f.text_area :last_name_kana,class:"form-control" %></td>
        <td><%= f.text_area :first_name_kana,class:"form-control" %></td>
      </tr>
      <tr>
        <td>郵便番号</td>
        <td><%= f.text_area :postal_code,class:"form-control" %></td>
      </tr>
      <tr>
        <td>住所</td>
        <td colspan="2"><%= f.text_area :address,class:"form-control" %></td>
      </tr>
      <tr>
        <td>電話番号</td>
        <td><%= f.text_area :telephone_number,class:"form-control" %></td>
      </tr>
      <tr>
        <td>メールアドレス</td>
        <td class="input-sm"><%= f.text_area :email,class:"form-control " %></td>
      </tr>
      <tr>
        <td>
          会員ステータス
        </td>
        <td>
          <%= f.radio_button :is_deleted, "false" %>
          <%= f.label :is_deleted, "有効" %>
          <%= f.radio_button :is_deleted, "true" %>
          <%= f.label :is_deleted, "退会" %>
        </td>
      </tr>
    </table>
  </div>
  <div class="row">
    <div class="col-12 text-center">
      <%= f.submit "変更を保存",class:"btn btn-success" %>
      <% end %>
    </div>
  </div>
</div>

app/views/admin/customers/index.html.erb
<div class="container">
  <div class="row">
    <h3 class="bg-light">会員一覧</h3>
  </div>
  <div class="row">
    <table class="table table-sm table-bordered">
      <thead class="bg-light">
        <tr>
          <th>会員ID</th>
          <th>氏名</th>
          <th>メールアドレス</th>
          <th>ステータス</th>
        </tr>
      </thead>
      <tbody>
        <% @customers.each do |customer| %>
        <tr>
          <td><%= customer.id %></td>
          <td>
            <%= link_to admin_customer_path(customer.id) do %>
              <%= customer.full_name %>
            <% end %>
          </td>
          <td><%= customer.email %></td>
          <td class="text-center"><%= customer.withdraw_status %></td>
        <% end %>
        </tr>
      </tbody>
    </table>
  </div>
  <%= paginate @customers %>
</div>

app/views/admin/customers/show.html.erb
<div class="container">
  <div class="row">
    <h3 class="bg-light"><%= @customer.full_name %>さんの会員詳細</h3>
  </div>
  <div class="row offset-1">
    <table class="table table-sm">
      <tr>
        <td>会員ID</td>
        <td><%= @customer.id %></td>
      </tr>
      <tr>
        <td>氏名</td>
        <td><%= @customer.full_name %></td>
      </tr>
      <tr>
        <td>フリガナ</td>
        <td><%= @customer.full_name_kana %></td>
      </tr>
      <tr>
        <td>郵便番号</td>
        <td><%= @customer.postal_code %></td>
      </tr>
      <tr>
        <td>住所</td>
        <td><%= @customer.address %></td>
      </tr>
      <tr>
        <td>電話番号</td>
        <td><%= @customer.telephone_number %></td>
      </tr>
      <tr>
        <td>メールアドレス</td>
        <td><%= @customer.email %></td>
      </tr>
      <tr>
        <td>会員ステータス</td>
        <td><%= @customer.withdraw_status %></td>
      </tr>
    </table>
  </div>
  <div class="row offset-2">
    <%= link_to edit_admin_customer_path,class:"btn btn-success btn-sm" do %>
      編集する
    <% end %>
    <%= link_to admin_root_path,class:"btn btn-primary btn-sm ml-5" do %>
      注文履歴一覧を見る
    <% end %>
  </div>
</div>

app/views/admin/items/edit.html.erb
<div class="container">
  <div class="row">
    <h3 class="bg-light">商品編集</h3>
  </div>
  <%= form_with model: @item, url: admin_item_path, method: :patch do |f| %>
  <div class="row">
    <table class="table table-borderless table-sm">
      <tr>
        <div class="field">
          <td class="font-weight-bold">商品画像</td>
          <td><%= f.file_field :image %></td>
        </div>
      </tr>
      <tr>
        <div class="field">
          <td class="font-weight-bold">商品名</td>
          <td><%= f.text_area :name %></td>
        </div>
      </tr>
      <tr>
        <div class="field">
          <td class="font-weight-bold">商品説明</td>
          <td><%= f.text_area :introduction %></td>
        </div>
      </tr>
      <tr>
        <div class="field">
          <td class="font-weight-bold">税抜価格</td>
          <td><%= f.text_area :price %>円</td>
        </div>
      </tr>
    </table>
  </div>
  <div class="row">
    <%= f.submit "変更を保存",class:"btn btn-success" %>
    <% end %>
  </div>
</div>

app/views/admin/items/index.html.erb
<div class="container">
  <div class="row">
    <h3 class="bg-light">商品一覧</h3>
    <%= link_to new_admin_item_path,class:"btn ml-auto mr-3" do %>
      <i class="fa-solid fa-circle-plus fa-lg" style="color: #c6c3c3;"></i>
    <% end %>
  </div>
  <div class="row">
    <table class="table table-sm">
      <thead class="bg-light">
        <tr>
          <th>商品ID</th>
          <th>商品名</th>
          <th>税抜価格</th>
        </tr>
      </thead>
      <tbody>
        <% @items.each do |item|%>
        <tr>
          <td><%= item.id %></td>
          <td>
            <%= link_to admin_item_path(item.id) do %>
              <%= item.name %>
            <% end %>
          </td>
          <td><%= item.price %></td>
        <% end %>
        </tr>
      </tbody>
    </table>
  </div>
  <div class="row">
    <%= paginate @items %>
  </div>
</div>

app/views/admin/items/new.html.erb
<div class="container">
  <div class="row">
    <h3 class="bg-light">商品新規登録</h3>
  </div>
  <div class="row">
    <% if @item.errors.any? %>
      <%= @item.errors.count %>件のエラーが発生しました。
      <ul>
        <% @item.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    <% end %>
  </div>

  <%= form_with model: @item, url: admin_items_path do |f| %>
  <div class="row">
    <table class="table table-borderless table-sm">
      <tr>
        <td class="font-weight-bold"><%= f.label :商品画像 %></td>
        <td><%= f.file_field :image, accept: "image/*" %></td>
      </tr>
      <tr>
        <td class="font-weight-bold"><%= f.label :商品名 %></td>
        <td><%= f.text_area :name %></td>
      </tr>
      <tr>
        <td class="font-weight-bold"><%= f.label :商品説明 %></td>
        <td><%= f.text_area :introduction %></td>
      </tr>
      <tr>
        <td class="font-weight-bold"><%= f.label :税抜価格 %></td>
        <td><%= f.text_area :price %>円</td>
      </tr>
    </table>
  </div>
  <%= f.submit "新規登録",class:"btn btn-success" %>
  <% end %>
</div>

app/views/admin/items/show.html.erb
<div class="container">
  <div class="row">
    <h3 class="bg-light">商品詳細</h3>
  </div>
  <div class="row">
    <div class="col-5 text-center d-flex align-middle">
      <%= image_tag @item.image, size:"250x250" %>
    </div>
    <div class="col-7">
      <table class="table table-borderless table-sm">
        <tr>
          <td class="font-weight-bold">商品名</td>
          <td><%= @item.name %></td>
        </tr>
        <tr>
          <td class="font-weight-bold">商品説明</td>
          <td><%= @item.introduction %></td>
        </tr>
        <tr>
          <td class="font-weight-bold">
            税込価格</br>
            (税抜価格)
          </td>
          <td class="align-middle"><%= @item.with_tax_price %>(<%= @item.price %>)円</td>
        </tr>
      </table>
    </div>
  </div>
  <div class="row">
    <div class="col-12 text-center">
      <%= link_to edit_admin_item_path,class:"btn btn-success" do %>
        編集する
      <% end %>
    </div>
  </div>
</div>

app/views/admin/orders/show.html.erb
<div class="container">
  <div class="row">
    <h3 class="bg-light">注文履歴詳細</h3>
  </div>
  <div class="row offset-1">
    <table class="table table-bordered table-sm">
      <tr>
        <td class="bg-light font-weight-bold">購入者</td>
        <td><%= @order.customer.full_name %></td>
      </tr>
      <tr>
        <td class="bg-light font-weight-bold">注文日</td>
        <td><%= @order.created_at.strftime('%Y/%m/%d') %></td>
      </tr>
      <tr>
        <td class="bg-light font-weight-bold">配送先</td>
        <td>
          〒<%= @order.customer.postal_code + ' ' + @order.customer.address %><br />
          <%= @order.customer.full_name %>
        </td>
      </tr>
      <tr>
        <td class="bg-light font-weight-bold">支払方法</td>
        <td><%= @order.payment_method_i18n %></td>
      </tr>
    </table>
  </div>

  <div class="row offset-1">
    <table class="table table-sm">
      <thead class="bg-light">
        <tr>
          <th>商品名</th>
          <th>単価(税込)</th>
          <th>数量</th>
          <th>小計</th>
        </tr>
      </thead>
      <tbody>
        <% @order.order_details.each do |order_detail| %>
        <tr>
          <td><%= order_detail.item.name %></td>
          <td><%= order_detail.item.with_tax_price %></td>
          <td><%= order_detail.amount %></td>
          <td>
            <%= order_detail.item.with_tax_price * order_detail.amount %>
            <% sub_total = order_detail.item.with_tax_price * order_detail.amount %>
            <% @total_price += sub_total %>
          </td>
        <% end %>
        </tr>
      </tbody>
    </table>
  </div>

  <div class="row offset-1">
    <table class="table table-bordered table-sm">
      <tr>
        <td class="bg-light font-weight-bold">商品合計</td>
        <td><%= @total_price %>円</td>
      </tr>
      <tr>
        <td class="bg-light font-weight-bold">送料</td>
        <td>800円</td>
      </tr>
      <tr>
        <td class="bg-light font-weight-bold">請求額合計</td>
        <td><%= @total_price.to_i + 800 %>円</td>
      </tr>
    </table>
  </div>
</div>