config/routes.rb
Rails.application.routes.draw do
  root to: "homes#top"
  get '/homes/about', as: "about"
  #顧客用
  # URL /customers/sign_in ...
  devise_for :customers, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

  scope module: :public do
    resources :items, only:[:index, :show]
    resources :cart_items, only:[:index, :update, :destroy, :create]do
      collection do
        delete 'destroy_all'
      end
    end
    resources :orders, only:[:new, :index, :show, :create]do
      collection do
        post 'confirm'
        get 'complete'
      end
    end
    get '/customers/my_page' => 'customers#show', as: "customer"
    get '/customers/information/edit' => 'customers#edit', as: "edit_customer"
    patch '/customers/information' => 'customers#update', as: "update_customer"
    get '/customers/unsubscribe', as: "unsubscribe_customer"
    patch '/customers/withdraw', as: "withdraw_customer"
  end

  #管理者用
  # URL /admin/sign_in ...
  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }
  namespace :admin do
    root to: "homes#top"
    resources :items, only:[:index, :new, :show, :edit, :create, :update]
    resources :customers, only:[:index, :show, :edit, :update]
    resources :orders, only:[:show, :update]
  end

end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  before_action :authenticate_admin!
  
  def top
    @orders = Order.page(params[:page]).per(10)
    @total_amount = 0
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
    @items = Item.limit(4).order(:created_at)
  end

  def about
  end
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/admin/homes/top.html.erb
<div class="container">
  <div class="row">
    <h3 class="bg-light">注文履歴一覧</h3>
  </div>
  <div class="row offset-1">
    <table class="table table-sm">
      <thead>
        <tr>
          <th class="text-center">購入日時</th>
          <th class="text-center">購入者</th>
          <th class="text-center">注文個数</th>
        </tr>
      </thead>
      <tbody>
        <% @orders.each do |order| %>
        <tr>
          <td class="text-center">
            <%= link_to admin_order_path(order.id) do %>
              <%= order.created_at.strftime('%Y/%m/%d %H:%M:%S') %>
            <% end %>
          </td>
          <td class="text-center"><%= order.customer.full_name %></td>
          <td class="text-center">
            <% order.order_details.each do |order_detail| %>
              <% order_detail.amount %>
              <% @total_amount += order_detail.amount %>
            <% end %>
            <%= @total_amount %>
            <% @total_amount = 0 %>
            </td>
        </tr>
        <% end %>
      </tbody>
    </table>
  </div>
  <div class="row">
    <%= paginate @orders %>
  </div>
</div>