config/routes.rb
Rails.application.routes.draw do
  root to: "homes#top"
  get '/homes/about', as: "about"
  #顧客用
  # URL /customers/sign_in ...
  devise_for :customers, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

  scope module: :public do
    resources :items, only:[:index, :show]
    resources :cart_items, only:[:index, :update, :destroy, :create]do
      collection do
        delete 'destroy_all'
      end
    end
    resources :orders, only:[:new, :index, :show, :create]do
      collection do
        post 'confirm'
        get 'complete'
      end
    end
    get '/customers/my_page' => 'customers#show', as: "customer"
    get '/customers/information/edit' => 'customers#edit', as: "edit_customer"
    patch '/customers/information' => 'customers#update', as: "update_customer"
    get '/customers/unsubscribe', as: "unsubscribe_customer"
    patch '/customers/withdraw', as: "withdraw_customer"
  end

  #管理者用
  # URL /admin/sign_in ...
  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }
  namespace :admin do
    root to: "homes#top"
    resources :items, only:[:index, :new, :show, :edit, :create, :update]
    resources :customers, only:[:index, :show, :edit, :update]
    resources :orders, only:[:show, :update]
  end

end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  before_action :authenticate_admin!
  
  def top
    @orders = Order.page(params[:page]).per(10)
    @total_amount = 0
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
    @items = Item.limit(4).order(:created_at)
  end

  def about
  end
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/homes/about.html.erb
<div class="contener">
  <div class="row">
    <div class="col-12 text-center">
      <h1 class="mb-4">About</h1>
      <p class="mb-0">ながのCAFEは全国発送可能なケーキ屋さんです。</p>
      <p class="mb-0">お子様からお年寄りの方までお召し上がりいただけるよう、</p>
      <p class="mb-0">様々なバリエーションをご用意しております。</p>
      <p class="mb-0">また、全国へ発送可能ですので「いつ」でも「どこ」でもご注文いただけます。</p>
      <p class="mb-0">ぜひご注文ください。</p>
    </div>
  </div>
</div>

app/views/homes/top.html.erb
<div class="container">
  <div class="row">
    <div class="col-12 text-center">
      <p>ようこそ、ながのCAKEへ！</p>
      <p>このサイトは、ケーキ販売のECサイトになります。</p>
      <p>会員でない方も商品の閲覧はできますが、</p>
      <p>購入には会員登録が必要になります。</p>
    </div>
  </div>
  <div class="row">
    <h2>新着商品</h2>
    </div>
    <div class="row">
      <% @items.each do |item| %>
      <div class="col-3">
        <div>
          <%= link_to item_path(item.id) do %>
            <%= image_tag item.image , size:"250x250"%>
          <% end %>
        </div>
        <div><%= item.name %></div>
        <div>￥<%= item.price %></div>
      </div>
      <% end %>
    </div>
    <div class="row">
      <%= link_to items_path do %>
        全ての商品を見る
      <% end %>
    </div>
  </div>
</div>