config/routes.rb
Rails.application.routes.draw do
  root to: "homes#top"
  get '/homes/about', as: "about"
  #顧客用
  # URL /customers/sign_in ...
  devise_for :customers, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

  scope module: :public do
    resources :items, only:[:index, :show]
    resources :cart_items, only:[:index, :update, :destroy, :create]do
      collection do
        delete 'destroy_all'
      end
    end
    resources :orders, only:[:new, :index, :show, :create]do
      collection do
        post 'confirm'
        get 'complete'
      end
    end
    get '/customers/my_page' => 'customers#show', as: "customer"
    get '/customers/information/edit' => 'customers#edit', as: "edit_customer"
    patch '/customers/information' => 'customers#update', as: "update_customer"
    get '/customers/unsubscribe', as: "unsubscribe_customer"
    patch '/customers/withdraw', as: "withdraw_customer"
  end

  #管理者用
  # URL /admin/sign_in ...
  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }
  namespace :admin do
    root to: "homes#top"
    resources :items, only:[:index, :new, :show, :edit, :create, :update]
    resources :customers, only:[:index, :show, :edit, :update]
    resources :orders, only:[:show, :update]
  end

end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  has_one_attached :image
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :customer
  belongs_to :item

  def sub_total
    item.with_tax_price * amount
  end
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :cart_items
  has_many :orders

  def full_name
    self.last_name + " " + self.first_name
  end

  def full_name_kana
    self.last_name_kana + " " + self.first_name_kana
  end

  def withdraw_status
    if is_deleted == false
      "有効"
    else
      "退会"
    end
  end
end

app/models/item.rb
class Item < ApplicationRecord
  has_many :cart_items
  has_many :order_details
  
  has_one_attached :image
  
  validates :image       , presence: true
  validates :name        , presence: true
  validates :introduction, presence: true
  validates :price       , presence: true

  def with_tax_price
    tax = 1.10
    (price * tax).round
  end
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :customer
  has_many :order_details
  
  enum payment_method: { credit_card: 0, transfer: 1}
  
end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
  belongs_to :order
  belongs_to :item
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  before_action :authenticate_admin!
  
  def top
    @orders = Order.page(params[:page]).per(10)
    @total_amount = 0
  end
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  before_action :authenticate_admin!
  
  def index
    @items = Item.page(params[:page]).per(10)
  end

  def new
    @item = Item.new
  end

  def create
    @item = Item.new(item_params)
    if @item.save
      redirect_to admin_item_path(@item.id)
    else
      render :new
    end
  end

  def show
    @item = Item.find(params[:id])
  end

  def edit
    @item = Item.find(params[:id])
  end

  def update
    @item = Item.find(params[:id])
    @item.update(item_params)
    redirect_to admin_item_path
  end


  private
  def item_params
    params.require(:item).permit(:image, :name, :introduction, :price)
  end
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
  before_action :authenticate_admin!

  def show
    @order = Order.find(params[:id])
    @total_price = 0
  end

  def update
  end
end

app/controllers/admin/sessions_controller.rb
# frozen_string_literal: true

class Admin::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # def after_sign_in_path_for(resource)
    # 注文履歴一覧（管理者トップページへ）
  # end

  def after_sign_out_path_for(resource)
    new_admin_session_path
  end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/admin/unlocks_controller.rb
# frozen_string_literal: true

class Admin::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
    @items = Item.limit(4).order(:created_at)
  end

  def about
  end
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/admin/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation" data-turbo-cache="false">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admin/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NaganoCafe</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <script src="https://kit.fontawesome.com/0d6e0ddc74.js" crossorigin="anonymous"></script>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <div class="container-fluid">
        <div class="row my-3">
          <div class="col-12">
            <nav class="navbar navbar-expand-md nabvar-dark bg-light">
              <%= link_to root_path, class: 'nav-brond nav-link text-dark' do %>
                <p class='lead mb-0'>
                  <strong>
                    Nagano
                    <i class="fa-solid fa-mug-hot"></i>
                    Cafe
                  </strong>
                </p>
              <% end %>
              <% if admin_signed_in? %>
                <ul class="navbar-nav ml-auto">
                  <li class="nav-item mr-2">
                    <%= link_to admin_items_path, class: 'nav-link btn btn-outline-dark' do %>
                      商品一覧
                    <% end %>
                  </li>
                  <li class="nav-item mr-2">
                    <%= link_to admin_customers_path, class: 'nav-link btn btn-outline-dark' do %>
                      会員一覧
                    <% end %>
                  </li>
                  <li class="nav-item mr-2">
                    <%= link_to admin_root_path, class: 'nav-link btn btn-outline-dark' do %>
                      注文履歴一覧
                    <% end %>
                  </li>
                  <li class="nav-item mr-2">
                    <%= link_to destroy_admin_session_path, method: :delete, class: 'nav-link btn btn-outline-dark' do %>
                      ログアウト
                    <% end %>
                  </li>
                </ul>
              <% elsif customer_signed_in? %>
                <p class="mb-0 ml-3">ようこそ、<%= current_customer.last_name %>さん！</p>
                <ul class="navbar-nav ml-auto">
                  <li class="nav-item mr-2">
                    <%= link_to customer_path, class: 'nav-link btn btn-outline-dark' do %>
                      マイページ
                    <% end %>
                  </li>
                  <li class="nav-item mr-2">
                    <%= link_to items_path, class: 'nav-link btn btn-outline-dark' do %>
                      商品一覧
                    <% end %>
                  </li>
                  <li class="nav-item mr-2">
                    <%= link_to cart_items_path, class: 'nav-link btn btn-outline-dark' do %>
                      カート
                    <% end %>
                  </li>
                  <li class="nav-item mr-2">
                    <%= link_to destroy_customer_session_path, method: :delete, class: 'nav-link btn btn-outline-dark' do %>
                      ログアウト
                    <% end %>
                  </li>
                </ul>
              <% else %>
                <ul class="navbar-nav ml-auto">
                  <li class="nav-item mr-2">
                    <%= link_to about_path, class: 'nav-link btn btn-outline-dark' do %>
                      About
                    <% end %>
                  </li>
                  <li class="nav-item mr-2">
                    <%= link_to items_path, class: 'nav-link btn btn-outline-dark' do %>
                      商品一覧
                    <% end %>
                  </li>
                  <li class="nav-item mr-2">
                    <%= link_to new_customer_registration_path, class: 'nav-link btn btn-outline-dark' do %>
                      新規登録
                    <% end %>
                  </li>
                  <li class="nav-item mr-2">
                    <%= link_to new_customer_session_path, class: 'nav-link btn btn-outline-dark' do %>
                      ログイン
                    <% end %>
                  </li>
                </ul>
              <% end %>
            </nav>
          </div>
        </div>
      </div>
    </header>
    <main>
      <%= yield %>
    </main>
    <footer>

    </footer>
  </body>
</html>